//
//  LearningInteractor.swift
//  LearnWithMe
//
//  Created by Zvonimir Medak on 12.12.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Combine

final class LearningInteractor {
}

// MARK: - Extensions -

extension LearningInteractor: LearningInteractorInterface {
}
