//
//  LearningInterfaces.swift
//  LearnWithMe
//
//  Created by Zvonimir Medak on 12.12.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import CombineExt

protocol LearningWireframeInterface: WireframeInterface {
    func navigateToQuestions(_ questions: QuestionDifficulty)
}

protocol LearningViewInterface: ViewInterface {
}

protocol LearningPresenterInterface: PresenterInterface {
    func configure(with output: Learning.ViewOutput) -> Learning.ViewInput
}

protocol LearningInteractorInterface: InteractorInterface {
}

enum Learning {

    struct ViewOutput {
        let previous: Signal<Void>
        let next: Signal<Void>
        let takeQuiz: Signal<Void>
    }

    struct ViewInput {
        let configurator: Driver<LearningConfigurator>
    }

}
