//
//  LearningWireframe.swift
//  LearnWithMe
//
//  Created by Zvonimir Medak on 12.12.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import CombineExt
import Combine

final class LearningWireframe: BaseWireframe<LearningViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Learning", bundle: nil)

    // MARK: - Module setup -

    init(questionsDifficulty: QuestionDifficulty) {
        let moduleViewController = storyboard.instantiateViewController(ofType: LearningViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = LearningInteractor()
        let presenter = LearningPresenter(
            view: moduleViewController,
            interactor: interactor,
            wireframe: self,
            questionDifficulty: questionsDifficulty
        )
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension LearningWireframe: LearningWireframeInterface {

    func navigateToQuestions(_ questions: QuestionDifficulty) {
        navigationController?.pushWireframe(QuizWireframe(questionDifficulty: questions))
    }
}
