//
//  QuizInteractor.swift
//  LearnWithMe
//
//  Created by Zvonimir Medak on 10.12.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class QuizInteractor {

    private let questionServiceable: QuestionServiceable

    init(questionServiceable: QuestionServiceable) {
        self.questionServiceable = questionServiceable
    }
}

// MARK: - Extensions -

extension QuizInteractor: QuizInteractorInterface {

    func save(_ answer: String) {
        questionServiceable.save(answer)
    }

    var result: String {
        questionServiceable.result
    }

    var nextQuestion: Question? {
        questionServiceable.nextQuestion
    }
}

