//
//  QuizWireframe.swift
//  LearnWithMe
//
//  Created by Zvonimir Medak on 10.12.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class QuizWireframe: BaseWireframe<QuizViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Quiz", bundle: nil)

    // MARK: - Module setup -

    init(questionDifficulty: QuestionDifficulty) {
        let moduleViewController = storyboard.instantiateViewController(ofType: QuizViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = QuizInteractor(questionServiceable: QuestionsService(questions: questionDifficulty))
        let presenter = QuizPresenter(
            view: moduleViewController,
            interactor: interactor,
            wireframe: self,
            questionDifficulty: questionDifficulty
        )
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension QuizWireframe: QuizWireframeInterface {
}
