//
//  HomeInterfaces.swift
//  LearnWithMe
//
//  Created by Zvonimir Medak on 05.12.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine

protocol HomeWireframeInterface: WireframeInterface {
    func navigateToLearning(_ questionDifficulty: QuestionDifficulty)
}

protocol HomeViewInterface: ViewInterface, Progressable {
    func showPickerView(_ item: HomeCollectionCellItem)
    func hidePickerView()
}

protocol HomePresenterInterface: PresenterInterface {
    func configure(with output: Home.ViewOutput) -> Home.ViewInput
}

protocol HomeInteractorInterface: InteractorInterface {
    var categoriesPublisher: AnyPublisher<[Category], LWMError> { get }
}

enum Home {

    struct ViewOutput {
    }

    struct ViewInput {
        let items: AnyPublisher<[CollectionCellItem]?, Never>
    }

}
