//
//  HomeInteractor.swift
//  LearnWithMe
//
//  Created by Zvonimir Medak on 05.12.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Combine

final class HomeInteractor {

    private let firebaseServiceable: FirestoreServiceable

    init(firebaseServiceable: FirestoreServiceable = FirestoreService.shared) {
        self.firebaseServiceable = firebaseServiceable
    }
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {

    var categoriesPublisher: AnyPublisher<[Category], LWMError> {
        firebaseServiceable.categoriesPublisher
    }
}
